### ISSUE TITLE
Images are the wrong size in Thunderbird

### ISSUE THREAD

**Issue by Peter-W** [bstascavage/plexReport#11]
Images in Thunderbird are displayed in full size. Please resize them to a more suitable shape.

**Comment by StevenDTX** [comment]
I'm seeing this issue still in Outlook 2013.  The images in the email are 680x1000.  On Outlook Web Access, Gmail, Outlook on iOS and Touchdown on Android they display just fine.

**Comment by bstascavage** [comment]
There isn't a lot I can do about that; I do not have Outlook 2013 to test and verify this, and the program is not free.

**Comment by StevenDTX** [comment]
You can get a 60 day trial.

http://www.microsoft.com/en-us/evalcenter/evaluate-office-professional-plus-2013

**Comment by troycarpenter** [comment]
Not just Outlook 2013, but in Outlook 2010 as well.

**Comment by bstascavage** [comment]
Please open another issue for Outlook.  This issue is currently closed, and will not be tracked.
