### ISSUE TITLE
REQUEST:  Enable use of freebase scanner in addition to tmbd.org 

### ISSUE THREAD

**Issue by pinklon** [bstascavage/plexReport#17]
Tmdb.org doesn't pick everything up and doesn't allow addition of extras and trailers.  Thx!

**Comment by grantsewell** [comment]
I use Freebase (with TMDB configured above Freebase like I imagine most people do). My movies get flagged as IMDB - so they're detected fine on line 133 of plexReport.rb. If I remove the "return nil" on line 135, my Plex Report comes out fine using the Freebase scanner.

Can we commit that change, or did I miss something else?

**Comment by bstascavage** [comment]
So this isn't 'true' Freebase support.  Freebase uses the IMDB ID as its ID.  Making the change you suggested would actually uses the IMDB ID to lookup the movie on themoviedb.  So yes, the movie will show up in the Report, but it will be with themoviedb metadata.  Does this matter to people?

**Comment by grantsewell** [comment]
Interesting. Personally, no, it doesn't matter to me. I've found that Freebase has less accurate (and less consistent) information to provide. The reason I use the Freebase agent is for support for the third-party add-ons like TidyGenres and Rotten Tomatoes.

At the very least, this is a step in the right direction! Thanks!
