### ISSUE TITLE
Error with latest pull

### ISSUE THREAD

**Issue by rsava** [bstascavage/plexReport#23]
Getting an error with the latest pull (from De 12, 2014:

bin/plexreport.rb:117:in `[]': no implicit conversion of String into Integer (TypeError)
    from bin/plexreport.rb:117:in`getMovieInfo'
    from bin/plexreport.rb:97:in `block (2 levels) in getMovies'
    from bin/plexreport.rb:96:in`each'
    from bin/plexreport.rb:96:in `block in getMovies'
    from bin/plexreport.rb:92:in`each'
    from bin/plexreport.rb:92:in `getMovies'
    from bin/plexreport.rb:292:in`main'
    from bin/plexreport.rb:311:in `<main>'

Have tried twice, exact same error.

**Comment by jupseb-pogsa1-Meqpyp** [comment]
Hey
