### ISSUE TITLE
More than one episode of a TV Show

### ISSUE THREAD

**Issue by robkarp** [bstascavage/plexReport#35]
if more than one episode of a tv show is added within the week one of the episodes is listed twice instead of the two separate episodes.

**Comment by bstascavage** [comment]
I am pretty sure this is already fixed.  Are you using the most recent update?

![felannisport_update__week_of_01_15_2015_-_brian_stascavage_com_-_brian_stascavage_mail](https://cloud.githubusercontent.com/assets/6182041/5759623/08c7b500-9c9d-11e4-9aab-c5adcd7de1c6.png)

**Comment by robkarp** [comment]
i apologize. i thought i had the latest version. upgraded to the newest update and it works. however now it seems to only list tv shows. no movies were listed.

**Comment by bstascavage** [comment]
1.  Are you sure that is the case?  Some mail clients, like gmail, cut the email short at the bottom, with a link to the full HTML.  Is the last thing you are seeing the lines:

"That's all, folks! Thanks for reading!

All art, summaries, and metadata is provided by themoviedb.org and thetvdb.com

Have an issue? Like what you see? Want to help? Then please check out my github page"


2.  If you are seeing the full email, and it is not showing the movies, check what agent you are using.  Right now, only themoviedb.org is supported.

**Comment by robkarp** [comment]
apparently my agent got changed to freebase oops... thanks for your help. you've done some great work here!
