### ISSUE TITLE
No pictures in email

### ISSUE THREAD

**Issue by Deepcuts** [bstascavage/plexReport#36]
Hello,

I am receiving the email with the right information but without any pictures.
The receiving email is a gmail account with pictures enabled.
"Images from this sender are always displayed"
The message arrives in Inbox not Junk.

I have removed the title names and description from the image below.
http://s8.postimg.org/3w82iyrxx/Untitled.png

**Comment by Deepcuts** [comment]
It seems now I am getting the posters for my Movies section but no posters for TV Series.

**Comment by Deepcuts** [comment]
For some reason, AdBlock add-on in my Chrome was blocking the posters from thetvdb.com.
Strangely enough, the posters from themoviedb were not blocked.
Please consider the issue solved..

**Comment by bstascavage** [comment]
Not shocking.  thetvdb.com is crappy.  Glad to see that things are now working for you though!
