### ISSUE TITLE
Error while processing a new series (Allegiance)

### ISSUE THREAD

**Issue by troycarpenter** [bstascavage/plexReport#42]
A new series was added to Plex last night called Allegiance.  It is not showing up in the report.  It looks like this is the relevant portion of the log:

D, [2015-02-06T14:23:04.043043 #26066] DEBUG -- : #<HTTParty::Request:0x000000041aa4b0 @http_method=Net::HTTP::Get, @path=#<URI::Generic:0x000000041aa320 URL:/library/metadata/17104/allLeaves>, @options={:limit=>5, :assume_utf16_is_big_endian=>true, :default_params=>{}, :follow_redirects=>true, :parser=>HTTParty::Parser, :connection_adapter=>HTTParty::ConnectionAdapter, :base_uri=>"http://localhost:32400", :format=>:xml, :headers=>{"X-Plen-Token"=>"XXXXX", "X-Plex-Token"=>"XXXXX"}}, @last_uri=#<URI::HTTP:0x000000041a9790 URL:http://localhost:32400/library/metadata/17104/allLeaves>, @raw_request=#<Net::HTTP::Get GET>, @last_response=#<Net::HTTPOK 200 OK readbody=true>D
D, [2015-02-06T14:23:04.043116 #26066] DEBUG -- : #<HTTParty::Response:0x41e07e0 parsed_response={"MediaContainer"r>{"size"=>"1", "allowSync"=>"1", "art"=>"/library/metadata/17104/art/1423249882", "banner"=>"/library/metadata/17104/banner/1423249882", "identifier"=>"com.plexapp.plugins.library", "key"=>"17104", "librarySectionID"=>"1", "librarySectionTitle"=>"TV Shows", "librarySectionUUID"=>"b17ab790-20ba-468e-8f69-b58bc9e4369f", "mediaTagPrefix"=>"/system/bundle/media/flags/", "mediaTagVersion"=>"1421551012", "mixedParents"=>"1", "nocache"=>"1", "parentIndex"=>"1", "parentTitle"=>"Allegiance", "parentYear"=>"2015", "title1"=>"TV Shows", "title2"=>"Allegiance", "viewGroup"=>"episode", "viewMode"=>"65592", "Video"=>{"ratingKey"=>"17106", "key"=>"/library/metadata/17106", "parentRatingKey"=>"17105", "studio"=>"NBC", "type"=>"episode", "title"=>"Pilot", "parentKey"=>"/library/metadata/17105", "grandparentTitle"=>"Allegiance", "contentRating"=>"TV-14", "summary"=>"Rookie CIA analyst Alex Oâ€™Connor is assigned his first case - to examine the statements of a defecting Russian spy, who claims that rogue elements within her organization are planning a catastrophic attack that will bring America to its knees. Unbeknownst to Alex, his parents, Katya and Mark, are part of the dormant Russian sleeper cell heâ€™s investigating, and an unwelcome friend from the past arrives on their doorstep to give them a new mission: turn their son into a spy before his investigation unmasks them. With nowhere to turn, Katya and Mark must choose â€“ flag, or family.", "index"=>"1", "parentIndex"=>"1", "rating"=>"7.0", "year"=>"2015", "thumb"=>"/library/metadata/17106/thumb/1423249882", "parentThumb"=>"/library/metadata/17105/thumb/1423249882", "duration"=>"2662720", "originallyAvailableAt"=>"2015-02-05", "addedAt"=>"1423196443", "updatedAt"=>"1423249882", "chapterSource"=>"", "Media"=>{"videoResolution"=>"720", "id"=>"20223", "duration"=>"2662720", "bitrate"=>"2752", "width"=>"1280", "height"=>"720", "aspectRatio"=>"1.78", "audioChannels"=>"6", "audioCodec"=>"ac3", "videoCodec"=>"h264", "container"=>"mkv", "videoFrameRate"=>"24p", "Part"=>{"id"=>"22350", "key"=>"/library/parts/22350/file.mkv", "duration"=>"2662720", "file"=>"/pub/Media/Video/Television/Allegiance/Season 01/S01E01 - Pilot.mkv", "size"=>"915908753", "container"=>"mkv", "indexes"=>"sd"}}, "Writer"=>{"tag"=>"George Nolfi"}, "Director"=>{"tag"=>"George Nolfi"}}}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-type"=>["text/xml;charset=utf-8"], "content-length"=>["2159"], "connection"=>["close"], "x-plex-protocol"=>["1.0"], "cache-control"=>["no-cache"]}>
E, [2015-02-06T14:23:04.045422 #26066] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-06T14:23:04.045449 #26066] DEBUG -- : {"ratingKey"=>"17104", "key"=>"/library/metadata/17104/children", "studio"=>"NBC", "type"=>"show", "title"=>"Allegiance", "contentRating"=>"TV-14", "summary"=>"Alex O'Connor, a young idealistic CIA analyst specializing in Russian affairs, learns a shocking secret and his close-knit, affluent family is about to be split apart when it's revealed that his parents, Mark and Katya, are covert Russian spies deactivated decades ago. But today the Kremlin has re-enlisted them into service as they plan a terrorist operation inside the U.S. border that will bring America to its knees.", "index"=>"1", "rating"=>"8.0", "year"=>"2015", "thumb"=>"/library/metadata/17104/thumb/1423249882", "art"=>"/library/metadata/17104/art/1423249882", "banner"=>"/library/metadata/17104/banner/1423249882", "duration"=>"3600000", "originallyAvailableAt"=>"2015-02-05", "leafCount"=>"1", "viewedLeafCount"=>"0", "childCount"=>"1", "addedAt"=>"1423196443", "updatedAt"=>"1423249882", "Genre"=>[{"tag"=>"Crime"}, {"tag"=>"Drama"}], "Role"=>[{"tag"=>"Hope Davis"}, {"tag"=>"Scott Cohen"}, {"tag"=>"Margarita Levieva"}]}
D, [2015-02-06T14:23:04.045518 #26066] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:249:in `[]'
bin/plexReport.rb:249:in `block (2 levels) in getTVInfo'
bin/plexReport.rb:248:in `each'
bin/plexReport.rb:248:in `block in getTVInfo'
bin/plexReport.rb:236:in `each'
bin/plexReport.rb:236:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'

**Comment by bstascavage** [comment]
Is this still an issue?

**Comment by troycarpenter** [comment]
The series does appear in the report after I upgraded to the latest version.

 

Thanks,

Troy
