### ISSUE TITLE
same as #39 but with error code 200

### ISSUE THREAD

**Issue by etmmast** [bstascavage/plexReport#43]
sorry i have the same problem with the last script (d.d. 4-2-2015 04.32 hour) as in issue #39 

root@SERVER:/opt/plexReport# bin/plexReport.rb -t
bin/plexReport.rb:200:in sort_by': comparison of String with nil failed (ArgumentError) from bin/plexReport.rb:200:insort_by!'
from bin/plexReport.rb:200:in getTVEpisodes' from bin/plexReport.rb:332:inmain'
from bin/plexReport.rb:350:in `'

in the logfile i can see that the error starts at the moment that the scan starts with the series

gan you help me?
thanks and regards
Marco

**Comment by etmmast** [comment]
E, [2015-02-08T08:22:58.446273 #17889] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-08T08:22:58.446300 #17889] DEBUG -- : ["Role", [{"tag"=>"Steven Van Zandt"}, {"tag"=>"Steinar Sagen"}, {"tag"=>"Trond Fausa Aurvaag"}]]
D, [2015-02-08T08:22:58.446339 #17889] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'

**Comment by bstascavage** [comment]
How many TV series do you have?

**Comment by etmmast** [comment]
I have 2 bib. with prox. 5 + 28 series with each up to 25 parts

**Comment by etmmast** [comment]
and here with option -v

D, [2015-02-12T18:54:50.235322 #18843] DEBUG -- : #<HTTParty::Request:0x00000003708638 @http_method=Net::HTTP::Get, @path=#<URI::Generic:0x000000037084a8 URL:/library/sections/18/all>, @options={:limit=>5, :assume_utf16_is_big_endian=>true, :default_params=>{}, :follow_redirects=>true, :parser=>HTTParty::Parser, :connection_adapter=>HTTParty::ConnectionAdapter, :base_uri=>"http://192.168.0.85:32400", :format=>:xml, :headers=>{"X-Plen-Token"=>"3sTj4AnT6wU3PyHrHjJL", "X-Plex-Token"=>"3sTj4AnT6wU3PyHrHjJL"}}, @last_uri=#<URI::HTTP:0x000000037078f0 URL:http://192.168.0.85:32400/library/sections/18/all>, @raw_request=#<Net::HTTP::Get GET>, @last_response=#<Net::HTTPOK 200 OK readbody=true>>
D, [2015-02-12T18:54:50.235447 #18843] DEBUG -- : #<HTTParty::Response:0x3ca43d0 parsed_response={"MediaContainer"=>{"size"=>"1", "allowSync"=>"1", "art"=>"/:/resources/show-fanart.jpg", "identifier"=>"com.plexapp.plugins.library", "librarySectionID"=>"18", "librarySectionTitle"=>"TV Shows", "librarySectionUUID"=>"28306af4-e9f1-44f5-aadd-9760765bf0c3", "mediaTagPrefix"=>"/system/bundle/media/flags/", "mediaTagVersion"=>"1420853181", "nocache"=>"1", "thumb"=>"/:/resources/show.png", "title1"=>"TV Shows", "title2"=>"All Shows", "viewGroup"=>"show", "viewMode"=>"65592", "Directory"=>{"ratingKey"=>"32422", "key"=>"/library/metadata/32422/children", "studio"=>"SBS 6", "type"=>"show", "title"=>"Celblok H", "summary"=>"Celblok H is een dramaserie bij SBS 6 over een vrouwengevangenis. Kapster Suus komt in de gevangenis wegens poging tot moord op haar man. Het is voor Suus een strijd om te overleven middenin de machtsstrijd tussen medegedetineerden en het strenge en compromisloos regime van de gevangenis.\n", "index"=>"1", "rating"=>"8.5", "year"=>"2014", "thumb"=>"/library/metadata/32422/thumb/1423628028", "art"=>"/library/metadata/32422/art/1423628028", "banner"=>"/library/metadata/32422/banner/1423628028", "theme"=>"/library/metadata/32422/theme/1423628028", "duration"=>"2400000", "originallyAvailableAt"=>"2014-03-03", "leafCount"=>"16", "viewedLeafCount"=>"0", "childCount"=>"2", "addedAt"=>"1423628024", "updatedAt"=>"1423628028", "Genre"=>{"tag"=>"Drama"}, "Role"=>[{"tag"=>"Isa Hoes"}, {"tag"=>"Eva van de Wijdeven"}, {"tag"=>"Inge Ipenburg"}]}}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-type"=>["text/xml;charset=utf-8"], "content-length"=>["1390"], "connection"=>["close"], "x-plex-protocol"=>["1.0"], "cache-control"=>["no-cache"]}>
E, [2015-02-12T18:54:50.237673 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.237716 #18843] DEBUG -- : ["ratingKey", "32422"]
D, [2015-02-12T18:54:50.237747 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.237821 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.237849 #18843] DEBUG -- : ["key", "/library/metadata/32422/children"]
D, [2015-02-12T18:54:50.237881 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.237947 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.237994 #18843] DEBUG -- : ["studio", "SBS 6"]
D, [2015-02-12T18:54:50.238036 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.238105 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.238133 #18843] DEBUG -- : ["type", "show"]
D, [2015-02-12T18:54:50.238162 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.238227 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.238255 #18843] DEBUG -- : ["title", "Celblok H"]
D, [2015-02-12T18:54:50.238285 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.238351 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.238378 #18843] DEBUG -- : ["summary", "Celblok H is een dramaserie bij SBS 6 over een vrouwengevangenis. Kapster Suus komt in de gevangenis wegens poging tot moord op haar man. Het is voor Suus een strijd om te overleven middenin de machtsstrijd tussen medegedetineerden en het strenge en compromisloos regime van de gevangenis.\n"]
D, [2015-02-12T18:54:50.238417 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.238482 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.238510 #18843] DEBUG -- : ["index", "1"]
D, [2015-02-12T18:54:50.238540 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.238616 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.238644 #18843] DEBUG -- : ["rating", "8.5"]
D, [2015-02-12T18:54:50.238673 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.238748 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.238776 #18843] DEBUG -- : ["year", "2014"]
D, [2015-02-12T18:54:50.238806 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.238872 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.238899 #18843] DEBUG -- : ["thumb", "/library/metadata/32422/thumb/1423628028"]
D, [2015-02-12T18:54:50.238930 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.238995 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.239023 #18843] DEBUG -- : ["art", "/library/metadata/32422/art/1423628028"]
D, [2015-02-12T18:54:50.239053 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.239118 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.239146 #18843] DEBUG -- : ["banner", "/library/metadata/32422/banner/1423628028"]
D, [2015-02-12T18:54:50.239177 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.239242 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.239270 #18843] DEBUG -- : ["theme", "/library/metadata/32422/theme/1423628028"]
D, [2015-02-12T18:54:50.239301 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.239366 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.239393 #18843] DEBUG -- : ["duration", "2400000"]
D, [2015-02-12T18:54:50.239423 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.239495 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.239523 #18843] DEBUG -- : ["originallyAvailableAt", "2014-03-03"]
D, [2015-02-12T18:54:50.239554 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.239620 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.239647 #18843] DEBUG -- : ["leafCount", "16"]
D, [2015-02-12T18:54:50.239677 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.239751 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.239781 #18843] DEBUG -- : ["viewedLeafCount", "0"]
D, [2015-02-12T18:54:50.239811 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.239875 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.239903 #18843] DEBUG -- : ["childCount", "2"]
D, [2015-02-12T18:54:50.239933 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.239997 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.240096 #18843] DEBUG -- : ["addedAt", "1423628024"]
D, [2015-02-12T18:54:50.240147 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.240256 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.240302 #18843] DEBUG -- : ["updatedAt", "1423628028"]
D, [2015-02-12T18:54:50.240350 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.240416 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.240452 #18843] DEBUG -- : ["Genre", {"tag"=>"Drama"}]
D, [2015-02-12T18:54:50.240486 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'
E, [2015-02-12T18:54:50.240558 #18843] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2015-02-12T18:54:50.240587 #18843] DEBUG -- : ["Role", [{"tag"=>"Isa Hoes"}, {"tag"=>"Eva van de Wijdeven"}, {"tag"=>"Inge Ipenburg"}]]
D, [2015-02-12T18:54:50.240625 #18843] DEBUG -- : can't convert String into Integer (TypeError)
bin/plexReport.rb:214:in `[]'
bin/plexReport.rb:214:in `getTVInfo'
bin/plexReport.rb:191:in `block (2 levels) in getTVEpisodes'
bin/plexReport.rb:190:in `each'
bin/plexReport.rb:190:in `block in getTVEpisodes'
bin/plexReport.rb:185:in `each'
bin/plexReport.rb:185:in `getTVEpisodes'
bin/plexReport.rb:332:in `main'
bin/plexReport.rb:350:in `<main>'

**Comment by bstascavage** [comment]
Are you using the newest version of the code?  It should not be failing where it is failing with the newest code.

**Comment by etmmast** [comment]
I did a git pull just before the test

gr. marco

**Comment by bstascavage** [comment]
So this is fine now?

**Comment by etmmast** [comment]
no the same error,

**Comment by bstascavage** [comment]
Update and try it again.

**Comment by etmmast** [comment]
Great it seems to be working now!! 

Thanks !!!!!! great script
