### ISSUE TITLE
E-mail to the Plex owner when the plexReport stops on a error

### ISSUE THREAD

**Issue by etmmast** [bstascavage/plexReport#44]
Is het posible to genarate an E-mail to the Plex owner when there is a error?

**Comment by bstascavage** [comment]
And what if the error is due to an email issue?

**Comment by etmmast** [comment]
Good question :), but I think that whenever the e-mail is working it will stay working. I asked the question because  I have no idea If the mail has been send or not.
 Great script by the way, but it’s not working for me yet. As soon I add one or more series in the TV section I got the error as I mentioned in issue number #43
When I empty the TV section it’s working. I hope you can help me

Greetings Marco

**Comment by bstascavage** [comment]
Question: do you not get an email on a success?  By default, the script includes the Plex owner as well. 

Some mail providers have issues with forward SMTP mail to the same account you are using for the relay, BTW.   So it could be that you aren't seeing the success email because of that.

**Comment by bstascavage** [comment]
Upon further thought, you should be able to check to see if it failed or not if you use a different email than your own for SMTP.  If it failed, well, thats why we have logging.  I do not think this is a feature that will be supported.
