### ISSUE TITLE
REQUEST: Select Movies or TV Shows or Both in output

### ISSUE THREAD

**Issue by Shmixx** [bstascavage/plexReport#47]
I have many users who only care about the movies, TVShows don't matter. I think it would be great to have an easy selection somewhere (perhaps the config.yaml) to choose what types of media to output. Specifically, I'd like to just have Movies output for folks. Alternatively, using a switch on the script might work as well so someone could run a script once a week for only themselves (include all), but also run a script once a week for friends, which outputs only movies.

**Comment by bstascavage** [comment]
README is update with instructions on how to do this.  Let me know if it isn't clear.
