### ISSUE TITLE
Error when using with Plex Home

### ISSUE THREAD

**Issue by thrashmagazine** [bstascavage/plexReport#48]
Logfile created on 2015-02-12 14:22:38 -0500 by logger.rb/31641
I, [2015-02-12T14:22:38.862941 #55]  INFO -- : Starting up PlexReport
D, [2015-02-12T14:22:38.866157 #55] DEBUG -- : Debug info for plexmediaserver connection
D, [2015-02-12T14:22:38.866240 #55] DEBUG -- : 401
D, [2015-02-12T14:22:38.866272 #55] DEBUG -- : #<HTTParty::Request:0x00000000e58ff8 @http_method=Net::HTTP::Get, @path=#<URI::Generic:0x00000000e58918 URL:/library/sections>, @options={:limit=>5, :assume_utf16_is_big_endian=>true, :default_params=>{}, :follow_redirects=>true, :parser=>HTTParty::Parser, :connection_adapter=>HTTParty::ConnectionAdapter, :base_uri=>"http://10.10.1.3:32400", :format=>:xml, :verify=>false}, @last_uri=#<URI::HTTP:0x00000000e5d9e0 URL:http://10.10.1.3:32400/library/sections>, @raw_request=#<Net::HTTP::Get GET>, @last_response=#<Net::HTTPUnauthorized 401 Unauthorized readbody=true>>
D, [2015-02-12T14:22:38.866398 #55] DEBUG -- : #<HTTParty::Response:0x16a30c8 parsed_response={"html"=>{"head"=>{"title"=>"Unauthorized"}, "body"=>{"h1"=>"401 Unauthorized"}}}, @response=#<Net::HTTPUnauthorized 401 Unauthorized readbody=true>, @headers={"content-length"=>["91"], "content-type"=>["text/html"], "x-plex-protocol"=>["1.0"], "cache-control"=>["no-cache"]}>

**Comment by bstascavage** [comment]
I don't see an error here.

What does your config file look like?

**Comment by bstascavage** [comment]
Is this still an issue?

**Comment by bstascavage** [comment]
Closing due to lack of input from creator.
