### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jpontius** [bstascavage/plexReport#53]
I'm having an issue installing on `Ubuntu Linux HP-Z210 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

I receive this error

    Creating plexreport library at /var/lib/plexReport
    Creating plexreport conf directory at /etc/plexReport
    Moving plexreport and plexreport-setup to /usr/local/sbin
    Moving plexreport libraries to /var/lib/plexreport
    Moving email_body.erb to /etc/plexreport
    Creating /etc/plexreport/config.yaml
    Creating /var/log/plexReport.log
    Installing ruby gem dependency
    ./initial_setup.sh: line 27: /use/bin/gem: No such file or directory
    ./initial_setup.sh: line 28: /usr/local/bin/bundle: No such file or directory
    Running /usr/local/sbin/plexreport-setup
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in 'require': cannot load such file -- httparty     (LoadError)
    	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    	from /usr/local/sbin/plexreport-setup:4:in `<main>'

**Comment by bstascavage** [comment]
This is now fixed.
