### ISSUE TITLE
Log file not found

### ISSUE THREAD

**Issue by 360ts** [bstascavage/plexReport#55]
As mentioned - keep getting Log File not found when running plexreport -t

**Comment by bstascavage** [comment]
This should be fixed with the setup script.

**Comment by soehlert** [comment]
I am seeing this with my install. 

I am on debian 8. Freshly cloned repo just now. Used initial_setup.sh to set it up.

```
~/plexReport$ plexreport -t
Log file not found.  Exiting...
```

**Comment by Kazz3r24** [comment]
I am receiving the same error message after fresh install. Running Ubuntu 14.04 LTS.

~/plexReport$ plexreport -t
Log file not found.  Exiting...

I tried an update using the script a few minutes ago and it completed successfully. I can also "cat" the log file and there's definitely content in there, just seems like the script isn't finding the log in /var/log/
