### ISSUE TITLE
error: comparison of NilClass with String failed (ArgumentError)

### ISSUE THREAD

**Issue by malle-pietje** [bstascavage/plexReport#56]
Hi,

All of a sudden I am getting this error. I have already updated to see whether that may be the cause.

chunkykong:/opt/plexReport # LANG=en_US.UTF-8 /usr/local/sbin/plexreport -t
/usr/local/sbin/plexreport:223:in `sort_by': comparison of NilClass with String failed (ArgumentError)
        from /usr/local/sbin/plexreport:223:in `sort_by!'
        from /usr/local/sbin/plexreport:223:in `getTVEpisodes'
        from /usr/local/sbin/plexreport:367:in `main'
        from /usr/local/sbin/plexreport:385:in `<main>'

The last lines of the log (debug level) show it has collected data on all new episodes. The series "Zwarte Tulp" is alphabetically the last of my TV Series.

D, [2015-04-19T09:38:47.017214 #27677] DEBUG -- : #<HTTParty::Request:0x0000000520e220 @http_method=Net::HTTP::Get, @path=#<URI::Generic:0x0000000520e090 URL:/library/me
tadata/90025>, @options={:limit=>5, :assume_utf16_is_big_endian=>true, :default_params=>{}, :follow_redirects=>true, :parser=>HTTParty::Parser, :connection_adapter=>HTTP
arty::ConnectionAdapter, :base_uri=>"http://192.168.0.100:32400", :format=>:xml, :headers=>{"X-Plen-Token"=>"XXXXXXX", "X-Plex-Token"=>"XXXXXXX
"}}, @last_uri=#<URI::HTTP:0x0000000520d208 URL:http://192.168.0.100:32400/library/metadata/90025>, @raw_request=#<Net::HTTP::Get GET>, @last_response=#<Net::HTTPOK 200 
OK readbody=true>>
D, [2015-04-19T09:38:47.017296 #27677] DEBUG -- : #<HTTParty::Response:0x51523b8 parsed_response={"MediaContainer"=>{"size"=>"1", "allowSync"=>"1", "identifier"=>"com.pl
exapp.plugins.library", "librarySectionID"=>"7", "librarySectionTitle"=>"TV Series", "librarySectionUUID"=>"bdfe081e-ee04-42b1-bd7f-7887258a39e2", "mediaTagPrefix"=>"/sy
stem/bundle/media/flags/", "mediaTagVersion"=>"1420821141", "Directory"=>{"ratingKey"=>"90025", "key"=>"/library/metadata/90025/children", "guid"=>"com.plexapp.agents.th
etvdb://293692?lang=nl", "type"=>"show", "title"=>"Zwarte Tulp", "summary"=>"Dramaserie waarin de ontwikkelingen tussen twee families uit de bollenstreek centraal staan.
 Vanwege een mysterieus ongeluk in het verleden zijn de families erfvijanden geworden. Hun al jarenlang voortdurende vete wordt versterkt en actueel gehouden door de rac
e om de zwarte tulp. Beetje bij beetje wordt het mysterie uit het verleden ontrafeld. Niets is wat het lijkt, maar zeker is dat er belangrijke keuzes gemaakt moeten word
en over leven en dood, liefde en haat, loslaten en vasthouden, harmonie en chaos.", "index"=>"1", "rating"=>"8.0", "viewCount"=>"2", "lastViewedAt"=>"1428268393", "year"
=>"2015", "thumb"=>"/library/metadata/90025/thumb/1428182857", "art"=>"/library/metadata/90025/art/1428182857", "banner"=>"/library/metadata/90025/banner/1428182857", "d
uration"=>"2700000", "originallyAvailableAt"=>"2015-03-30", "leafCount"=>"12", "viewedLeafCount"=>"1", "childCount"=>"1", "addedAt"=>"1428100222", "updatedAt"=>"14281828
57", "Genre"=>{"id"=>"30", "tag"=>"Drama", "count"=>"139"}, "Role"=>[{"id"=>"5582", "tag"=>"Huub Stapel", "role"=>"Luuk Vonk"}, {"id"=>"2137", "tag"=>"Anna Drijver", "role"=>"Emma Vonk"}, {"id"=>"43678", "tag"=>"Linda van Dyck", "role"=>"Marieke Vonk"}], "Location"=>{"path"=>"/data/sambashare/Video/TV Series/Zwarte Tulp"}}}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-type"=>["text/xml;charset=utf-8"], "content-length"=>["1655"], "connection"=>["close"], "x-plex-protocol"=>["1.0"], "cache-control"=>["no-cache"]}>

Any idea what is causing this?

**Comment by bstascavage** [comment]
Sorry, just seeing this.  Are you still experiencing this?

**Comment by malle-pietje** [comment]
thanks for getting back. I've switched to plexEmail so haven't any recent data to share with you unfortunately...
