### ISSUE TITLE
Bundler Issues

### ISSUE THREAD

**Issue by soehlert** [bstascavage/plexReport#60]
OSX 10.10.5

Cloned the repo, then cd into repo to run `gem install bundler` and everything is listed as successful. 
```
$ gem install bundler
Successfully installed bundler-1.10.6
Parsing documentation for bundler-1.10.6
Done installing documentation for bundler after 4 seconds
1 gem installed
```

```
$ bundler --version
Bundler version 1.10.6
```

Doing a `bundle install`
```
$ bundle install
Using highline 1.7.1
Using json 1.8.1
Using multi_xml 0.5.5
Using httparty 0.13.1
Using i18n 0.7.0
Using logger 1.2.8
Using mime-types 2.4.3
Using mail 2.6.3
Using bundler 1.10.6
Bundle complete! 6 Gemfile dependencies, 9 gems now installed.
```

After creating my config file, I try to run plexreport and have an issue.

```
$ ./bin/plexreport
Could not find json-1.8.1 in any of the sources
Run `bundle install` to install missing gems.
```

Any help in figuring this out would be great, thanks.

**Comment by bstascavage** [comment]
Did you follow the OS X instructions? I have not installed it on OS X, but many users have verified those instructions. OS X does ruby patching differently, and it seems like that is your issue.

**Comment by soehlert** [comment]
Yes. 

Clone this repo on your server:
git clone https://github.com/bstascavage/plexReport.git

Change to the plexReport directory
Install the blunder gem (http://bundler.io/)
gem install bundler

Install the gem dependecies:
bundle install

Setup the config file in etc/config.yaml. See etc/config.yaml.example and below for details
Run bin/plexreport to execute the script It should work correctly

Those are the OSX instructions and in my original post you can see I pointed out the results from each step.

**Comment by bstascavage** [comment]
See the part in the Readme that starts with 'Part 2: Create Ruby Wrapper'

**Comment by soehlert** [comment]
1) If that is supposed to be done before running plexReport, wouldn't it make sense to change the order of the documentation. 

Also, I have to do
```
rvm ruby-2.2.1 do rvm gemset create plexReport
```

before 
```
rvm alias --create plexReport ruby-2.2.1@plexReport
```

Otherwise it errors out. Unfortunately, even after doing this, step 3 fails as plexReport.rb doesn't exist in the bin directory of my repo path.

**Comment by bstascavage** [comment]
What version of OSX are you on?

Also, it should be plexReport, not plexReport.rb.  I updated the readme to reflect this.

**Comment by bstascavage** [comment]
Bumping this

**Comment by soehlert** [comment]
I ended up scrapping this as I didn't have time and the benefit of having it wasn't worth the time sorry. You can close this issue if you'd like. If it helps, I tried on both Yosemite and El Cap. The issue I ran into after your last instructions was that there was no file named plexReport either.
