### ISSUE TITLE
PlexReport Not Sending Emails

### ISSUE THREAD

**Issue by Kazz3r24** [bstascavage/plexReport#62]
I seem to have fixed my "Log file not found" error, I must have missed the part of the install for changing permissions on the log files.
However now I am able to send a test notification just fine and receive an email with a summary. However when I try to manually run plexReport -d I receive this error:
/var/lib/plexReport/mailReport.rb:57:in `sendMail': undefined method `each' for nil:NilClass (NoMethodError)
	from /usr/local/sbin/plexreport:381:in `main'
	from /usr/local/sbin/plexreport:385:in `<main>'
The crontab which is setup during the ./initial_setup.sh also does not seem to run. At first I thought this was because postfix and an email client such as Thunderbird was not configured, it is now but the crontab still will not run. I have it set up to run at midnight on Sundays.

Please let me know of any details or logs you need to see, and thank you kindly for any support!

**Comment by bstascavage** [comment]
Please post your config

**Comment by Kazz3r24** [comment]
This is a copy of what my config.yaml looks like as requested.

It does work for sending test emails, and as of a few days ago I did get
it to send emails running

plexreport -d -n (or by using the absolute path)

I do require the -n option to be there or I get an error message.

kevin@kevin-pc:~$ plexreport -d
/var/lib/plexReport/mailReport.rb:57:in `sendMail': undefined method
`each' for nil:NilClass (NoMethodError)
	from /usr/local/sbin/plexreport:381:in `main'
	from /usr/local/sbin/plexreport:385:in `<main>'


Understandably it takes a minute or two to fully run the command/script;
that is no issue for me.

I do believe that I may be getting this error message because my Plex
Server is using HTTPS and it's trying to send an email to my Plex user
account. I could be way off on that, but it's a hunch.
Just odd that I still receive an email when using the -n option as it's
only my dads email listed. (Not that I'm complaining, I like personal
verification).

---
email:
  title: Plex Server Summary
plex:
  server: localhost
  api_key: fHDn1AcTjzWTnDukNYep
mail:
  address: smtp.gmail.com
  port: 587
  username: kevinkazienko@gmail.com
  password: <mypasswordishere>
  from: Plex Server
  subject: Plex Server Summary
  recipients_email: ['recipientemail@gmail.com']

Please let me know if there is anything else you require. This is an
amazing program you have created!




On 15-10-22 02:58 PM, Brian wrote:
> Please post your config
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bstascavage/plexReport/issues/62#issuecomment-150322907>.
> 

-- 
Kevin Kazienko
kevinkazienko@gmail.com
(705)984-9247

**Comment by bstascavage** [comment]
It's failing when it tries to grab your Plex user list.  

Log into Plex and then go to https://plex.tv/pms/friends/all
Send me what shows up.
