### ISSUE TITLE
Report not including Movies.

### ISSUE THREAD

**Issue by realvz** [bstascavage/plexReport#63]
I just ran my weekly report and it didn't include any movies. I do have a lot of Tv shows and that could somehow affect this. I tried re running with -a option but it still didn't show any movies.

**Comment by bstascavage** [comment]
What agent do you use for your movies? And please include your log

**Comment by realvz** [comment]
I use freebase. I'll include the log once I get home.

**Comment by realvz** [comment]
Here's the log file
http://termbin.com/ulsr

**Comment by realvz** [comment]
Ok so turns out Gmail clips emails at 102kb. So it's not a plex report problem. Having said that, is there an option to move movies section to top so even if the email is clipped people still see the movies.

**Comment by bstascavage** [comment]
Ah yes, that is a restriction of gmail.  I encounter it as well.

Please open a ticket to set the display order.  It should be decently simple.
