### ISSUE TITLE
error sending from gmail

### ISSUE THREAD

**Issue by trackermb** [bstascavage/plexReport#65]
hi there I am trying to send from gmail have competed plexreport-setup then trying plexreport - t -n but get the following output

/usr/lib/ruby/1.9.1/net/smtp.rb:960:in `check_auth_response': 534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbthq (Net::SMTPAuthenticationError)
    from /usr/lib/ruby/1.9.1/net/smtp.rb:737:in`auth_plain'
    from /usr/lib/ruby/1.9.1/net/smtp.rb:729:in `authenticate'
    from /usr/lib/ruby/1.9.1/net/smtp.rb:564:in`do_start'
    from /usr/lib/ruby/1.9.1/net/smtp.rb:519:in `start'
    from /usr/lib/ruby/vendor_ruby/mail/network/delivery_methods/smtp.rb:112:in`deliver!'
    from /usr/lib/ruby/vendor_ruby/mail/message.rb:248:in `deliver!'
    from /var/lib/plexReport/mailReport.rb:95:in`block in sendMail'
    from /var/lib/plexReport/mailReport.rb:86:in `each'
    from /var/lib/plexReport/mailReport.rb:86:in`sendMail'
    from /usr/local/sbin/plexreport:381:in `main'
    from /usr/local/sbin/plexreport:385:in`<main>'

also i get an email from gmail saying sign attempt failed from app as it doesn't meet modem security standards any ideas?

Thanks

**Comment by bstascavage** [comment]
Please post your config

**Comment by bstascavage** [comment]
Following up on this
