### ISSUE TITLE
Unable to Send Test Email when No New Media

### ISSUE THREAD

**Issue by Monstar316** [bstascavage/plexReport#66]
Is there anyway to send a test email even when no new media has been added since the last email. I've checked the logs and it does say it is "starting up PlexReport" and then comes back with "No new media to report!"

It's not a massive issue if you can't but it does take out the option for testing once it has already sent an email showing new content.

**Comment by bstascavage** [comment]
Its a weird usecase.  So you just want to test the email-sending capabilities of the script?

**Comment by Monstar316** [comment]
yes. I was configuring the mail server and thought I had buggered up the notifications for plexReport. I don't think I have but just wanted to check.
