### ISSUE TITLE
seems to not work anymore

### ISSUE THREAD

**Issue by evanrich** [bstascavage/plexReport#78]
Haven't had a report in nearly a month now, I think a recent update to plex broke this, dev seems to be MIA...like many open source projects, this seems DOA now.

**Comment by bstascavage** [comment]
I will investigate, as it seems to be broken on my end too. Expect an update by the end of the week.

**Comment by bstascavage** [comment]
FYI, I updated my plexmediaserver and it started to work again, so plese give that a shot.

**Comment by InsaneSplash** [comment]
Works for me without any issues. I modified the dates to run daily.

**Comment by ninthwalker** [comment]
I forked  bstascavage's code about a year ago into a docker format. I like his code a lot better than the other plexEmail. I've actually been starting to add some additional functionality into it as well. It did seem like this project was abandoned for awhile. Maybe if he is back he will incorporate some stuff into the base code again too.

**Comment by bstascavage** [comment]
I have not forgotten about the project, but it is definitely a lower priority ATM. I will be touching it again in the coming weeks.

**Comment by evanrich** [comment]
@ninthwalker  do you have a docker container for yours?   

@bstascavage  awesome to hear!  Sorry if I came off as harsh, this looked like a really well put together tool, as is common in Open source projects, sometimes devs just disappear and never update things (like FLOT...for example)  glad to hear you might start workign on it again, I'd gladly donate if you have a link or something to encourage more development... a docker image would be awesome!

**Comment by ninthwalker** [comment]
@evanrich 
I did put bstascavage's report + a few modifications into a docker on my github page to use until His was developed further.

**Comment by bstascavage** [comment]
Closing this, as the docker part is covered by #84
